steps:
  # 1. Build the unified container image (Frontend + Backend)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: [
      'build', 
      '--build-arg', 'VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}',
      '--build-arg', 'VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}',
      '--build-arg', 'VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}',
      '--build-arg', 'VITE_AUTH_ACTION_URL=${_VITE_AUTH_ACTION_URL}',
      '--build-arg', 'VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}',
      '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/patent-apps/first-pat-v2:$COMMIT_SHA', 
      '.'
    ]

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: [
      'push', 
      'europe-west2-docker.pkg.dev/$PROJECT_ID/patent-apps/first-pat-v2:$COMMIT_SHA'
    ]

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'first-pat-v2-api'
      - '--image'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/patent-apps/first-pat-v2:$COMMIT_SHA'
      - '--region'
      - 'europe-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/patent-apps/first-pat-v2:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
